Number Functions

		ROUND()  TRUNC()  MOD()  POWER()
		ABS()	 SIGN()   CEIL() FLOOR()
		
	-- +ve Check next value | >=5 +1 Else same value
	
SELECT ROUND (393.478,2) "ROUND_01"
	 , ROUND (393.472,2) "ROUND_02"
	 , ROUND (393.472,1) "ROUND_03"
	 , ROUND (393.432,1) "ROUND_04"
	 , ROUND (393.972,0) "ROUND_05"
	 , ROUND (393.432,0) "ROUND_06"
	 , ROUND (393.478  ) "ROUND_07"
	FROM dual;
	
	-- -ve | >=5     | -1   10 | -2  100 |-2   1000
	
SELECT ROUND(393.478,-1)"ROUND_01"
	 , ROUND(393.472,-1)"ROUND_02"
	 , ROUND(393.472,-2)"ROUND_03"
	 , ROUND(393.472,-2)"ROUND_04"
	 , ROUND(393.472,-3)"ROUND_05"
	 , ROUND(393.472,-3)"ROUND_06"
	 , ROUND(393.472,-3)"ROUND_07"
	 FROM dual;
	 
positive TRUNC
SELECT TRUNC (6943.4565,3) "TRUNC_01"
	  ,TRUNC (5236.4646,2) "TRUNC_02"
	  ,TRUNC (8555.8986,1) "TRUNC_03"
	 FROM DUAL;

SELECT MOD (10,3) , MOD(-20,9) FROM dual;

-- Write a query to get employee who are all having odd/even as their employee_id

SELECT POWER (2,2),POWER(5,5) FROM DUAL;

SELECT ABS(-10),ABS(1000) FROM DUAL;

SELECT SIGN (-90),SIGN (89) FROM DUAL;

SELECT SUM(id) FROM sign_tb WHERE SIGN(id) = 1;
SELECT SUM(id) FROM sign_tb WHERE SIGN(id) = -1;

SELECT CEIL(1.8),CEIL(1.3),FLOOR(1.8),FLOOR(1.3)
FROM DUAL;

DATE Functions
MONTHS_BETWEEN()

SELECT SYSDATE FROM DUAL;
SELECT SYSDATE + 10 FROM DUAL;
SELECT SYSDATE - 10 FROM DUAL;
SELECT ROUND(SYSDATE - TO_DATE('21-FEB-20'))
FROM DUAL;
SELECT ROUND (SYSDATE + TO_DATE('21-FEB-20'))
FROM DUAL;

NOTE: 
DATE + DATE = DATE;
DATE - NUMBER = DATE;
DATE - DATE = NUMBER;
DATE + DATE = ERROR; (ORA - 00975: date + date not allowed)

SELECT ROUND(MONTHS_BETWEEN(SYSDATE,'21-MAR-20')) || 'months' "MONTHS_BETWEEN" FROM DUAL;

FOR YEAR

SELECT ROUND(MONTHS_BETWEEN(SYSDATE,'21-MAR-20')/12) || 'years' "Age" FROM DUAL;

SELECT employee_id,first_name,hire_date,ROUND(MONTHS_BETWEEN(SYSDATE,hire_date)/12) || 'years' exp FROM employees
WHERE ROUND (MONTHS_BETWEEN(SYSDATE,hire_date)/12) > 25;

SELECT ADD_MONTHS(SYSDATE,3),ADD_MONTHS(SYSDATE,-3)
FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'friday') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'SUNDAY') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'tuesday') FROM DUAL;
SELECT NEXT_DAY(SYSDATE + (5*7)) FROM DUAL;
SELECT LAST_DAY(SYSDATE + 10) FROM DUAL;

SELECT SYSDATE,ROUND(SYSDATE,'MM'),ROUND(SYSDATE - 20,'MM')
FROM DUAL;

SELECT SYSDATE,ROUND(SYSDATE,'YY'),ROUND(SYSDATE + 200,'YY')
FROM DUAL;

SELECT * FROM employees WHERE hire_date BETWEEN TRUNC (TO_DATE('28-SEP-97'),'MM') 
AND ADD_MONTHS(TRUNC(TO_DATE('26-SEP-97'),'MM'),1)-1;

SELECT * FROM employees WHERE hire_date BETWEEN TRUNC (TO_DATE('28-SEP-97'),'YY') 
AND ADD_MONTHS(TRUNC(TO_DATE('26-SEP-97'),'YY'),12)-1;

--Task 
SELECT department_id FROM departments 
WHERE MOD(department_id , 2) = 0;

SELECT department_id FROM departments 
WHERE MOD(department_id , 2) = 1;